# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Number-Nary
version:      0.100
version_from: lib/Number/Nary.pm
installdirs:  site
requires:
    Carp:                          0
    List::MoreUtils:               0.09
    Sub::Exporter:                 0.9
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
