---
abstract: 'encode and decode numbers as n-ary strings'
author:
  - 'Ricardo Signes, C<< <rjbs at cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Number::Nary
name: Number-Nary
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Carp: 0
  List::MoreUtils: 0.09
  Sub::Exporter: 0.9
  Test::More: 0
  UDCode: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.108
