---
abstract: 'encode and decode numbers as n-ary strings'
author:
  - 'Ricardo Signes <rjbs@cpan.org>'
generated_by: 'Dist::Zilla version 1.100160'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Number-Nary
requires:
  Carp: 0
  ExtUtils::MakeMaker: 6.11
  List::MoreUtils: 0.09
  Scalar::Util: 0.90
  Sub::Exporter: 0
  Test::More: 0
  UDCode: 0
  perl: 5.006
resources:
  repository: http://github.com/rjbs/number-nary
version: 1.100311
